services:
  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:latest
    env_file:
      - pihole-exporter.env
    ports:
      - "9617:9617"
    logging:
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:9617/metrics"]
      interval: 300s
      retries: 5
      timeout: 10s
    restart: always